/**
 * PRA PDF — Processing Server Input & Output Validator
 * A PRAVERSE Company
 * Validates magic bytes (%PDF-), file sizes (<= 50 MB), and structural validity.
 */

import fs from 'fs';
import { PDFDocument } from 'pdf-lib';
import { PROCESSOR_CONFIG } from './config';

export class PdfValidator {
  /**
   * Validates input buffer before processing
   */
  public static validateInput(buffer: Buffer): {
    valid: boolean;
    errorCode?: string;
    errorMessage?: string;
  } {
    if (!buffer || buffer.length === 0) {
      return {
        valid: false,
        errorCode: 'EMPTY_FILE',
        errorMessage: 'The provided input file is empty (0 bytes).',
      };
    }

    if (buffer.length > PROCESSOR_CONFIG.maxFileSizeBytes) {
      return {
        valid: false,
        errorCode: 'FILE_TOO_LARGE',
        errorMessage: `Input file size (${(buffer.length / (1024 * 1024)).toFixed(
          2
        )} MB) exceeds server limit of ${PROCESSOR_CONFIG.maxFileSizeMb} MB.`,
      };
    }

    // Verify PDF magic header %PDF-
    const header = buffer.slice(0, 5).toString('ascii');
    if (header !== '%PDF-') {
      return {
        valid: false,
        errorCode: 'INVALID_PDF',
        errorMessage: 'Input file does not contain a valid PDF signature (%PDF-).',
      };
    }

    return { valid: true };
  }

  /**
   * Validates output file on disk after processing
   */
  public static async validateOutputFile(filePath: string): Promise<{
    valid: boolean;
    errorCode?: string;
    errorMessage?: string;
    sizeBytes?: number;
  }> {
    if (!fs.existsSync(filePath)) {
      return {
        valid: false,
        errorCode: 'PROCESSING_OUTPUT_INVALID',
        errorMessage: 'Output file was not generated by the processing engine.',
      };
    }

    const stat = fs.statSync(filePath);
    if (stat.size === 0) {
      return {
        valid: false,
        errorCode: 'PROCESSING_OUTPUT_INVALID',
        errorMessage: 'Output file is 0 bytes.',
      };
    }

    if (stat.size > PROCESSOR_CONFIG.maxFileSizeBytes) {
      return {
        valid: false,
        errorCode: 'FILE_TOO_LARGE',
        errorMessage: `Output file exceeds maximum limit of ${PROCESSOR_CONFIG.maxFileSizeMb} MB.`,
      };
    }

    // Read header for signature check
    const fd = fs.openSync(filePath, 'r');
    const headerBuf = Buffer.alloc(5);
    fs.readSync(fd, headerBuf, 0, 5, 0);
    fs.closeSync(fd);

    if (headerBuf.toString('ascii') !== '%PDF-') {
      return {
        valid: false,
        errorCode: 'PROCESSING_OUTPUT_INVALID',
        errorMessage: 'Output file is missing valid PDF header (%PDF-).',
      };
    }

    // Structural integrity test: attempt PDF parsing
    try {
      const fullBuffer = fs.readFileSync(filePath);
      await PDFDocument.load(fullBuffer, { ignoreEncryption: true });
    } catch (err: any) {
      return {
        valid: false,
        errorCode: 'PROCESSING_OUTPUT_INVALID',
        errorMessage: `Output PDF structure is corrupt or unreadable: ${err?.message}`,
      };
    }

    return { valid: true, sizeBytes: stat.size };
  }
}
